#-------------------------------------------------------------------------------
# libtorrent
#
# Author: 	Arvid Norberg, arvid@libtorrent.org
# Version: 	1.2.5
#
# http://libtorrent.org/
# https://github.com/arvidn/libtorrent
#
#-------------------------------------------------------------------------------

INCLUDEPATH += $$PWD/1.2.5/include

include($$PWD/libtorrent-config.pri)


# ==============================================================================
# Kademlia
# Distributed hash table for decentralized peer-to-peer computer networks
# designed by Petar Maymounkov and David Mazières in 2002
# ==============================================================================
LIBTORRENT_HEADERS += \
    $$PWD/1.2.5/include/libtorrent/kademlia/announce_flags.hpp \
    $$PWD/1.2.5/include/libtorrent/kademlia/dht_observer.hpp \
    $$PWD/1.2.5/include/libtorrent/kademlia/dht_settings.hpp \
    $$PWD/1.2.5/include/libtorrent/kademlia/dht_state.hpp \
    $$PWD/1.2.5/include/libtorrent/kademlia/dht_storage.hpp \
    $$PWD/1.2.5/include/libtorrent/kademlia/dht_tracker.hpp \
    $$PWD/1.2.5/include/libtorrent/kademlia/direct_request.hpp \
    $$PWD/1.2.5/include/libtorrent/kademlia/dos_blocker.hpp \
    $$PWD/1.2.5/include/libtorrent/kademlia/ed25519.hpp \
    $$PWD/1.2.5/include/libtorrent/kademlia/find_data.hpp \
    $$PWD/1.2.5/include/libtorrent/kademlia/get_item.hpp \
    $$PWD/1.2.5/include/libtorrent/kademlia/get_peers.hpp \
    $$PWD/1.2.5/include/libtorrent/kademlia/io.hpp \
    $$PWD/1.2.5/include/libtorrent/kademlia/item.hpp \
    $$PWD/1.2.5/include/libtorrent/kademlia/msg.hpp \
    $$PWD/1.2.5/include/libtorrent/kademlia/node.hpp \
    $$PWD/1.2.5/include/libtorrent/kademlia/node_entry.hpp \
    $$PWD/1.2.5/include/libtorrent/kademlia/node_id.hpp \
    $$PWD/1.2.5/include/libtorrent/kademlia/observer.hpp \
    $$PWD/1.2.5/include/libtorrent/kademlia/put_data.hpp \
    $$PWD/1.2.5/include/libtorrent/kademlia/refresh.hpp \
    $$PWD/1.2.5/include/libtorrent/kademlia/routing_table.hpp \
    $$PWD/1.2.5/include/libtorrent/kademlia/rpc_manager.hpp \
    $$PWD/1.2.5/include/libtorrent/kademlia/sample_infohashes.hpp \
    $$PWD/1.2.5/include/libtorrent/kademlia/traversal_algorithm.hpp \
    $$PWD/1.2.5/include/libtorrent/kademlia/types.hpp

LIBTORRENT_SOURCES += \
    $$PWD/1.2.5/src/kademlia/dht_state.cpp \
    $$PWD/1.2.5/src/kademlia/dht_storage.cpp \
    $$PWD/1.2.5/src/kademlia/dht_tracker.cpp \
    $$PWD/1.2.5/src/kademlia/find_data.cpp \
    $$PWD/1.2.5/src/kademlia/put_data.cpp \
    $$PWD/1.2.5/src/kademlia/msg.cpp \
    $$PWD/1.2.5/src/kademlia/node.cpp \
    $$PWD/1.2.5/src/kademlia/node_entry.cpp \
    $$PWD/1.2.5/src/kademlia/node_id.cpp \
    $$PWD/1.2.5/src/kademlia/refresh.cpp \
    $$PWD/1.2.5/src/kademlia/routing_table.cpp \
    $$PWD/1.2.5/src/kademlia/rpc_manager.cpp \
    $$PWD/1.2.5/src/kademlia/traversal_algorithm.cpp \
    $$PWD/1.2.5/src/kademlia/dos_blocker.cpp \
    $$PWD/1.2.5/src/kademlia/get_peers.cpp \
    $$PWD/1.2.5/src/kademlia/get_item.cpp \
    $$PWD/1.2.5/src/kademlia/item.cpp \
    $$PWD/1.2.5/src/kademlia/ed25519.cpp \
    $$PWD/1.2.5/src/kademlia/sample_infohashes.cpp \
    $$PWD/1.2.5/src/kademlia/dht_settings.cpp

LIBTORRENT_SOURCES += \
    $$PWD/1.2.5/src/../ed25519/src/add_scalar.cpp \
    $$PWD/1.2.5/src/../ed25519/src/fe.cpp \
    $$PWD/1.2.5/src/../ed25519/src/ge.cpp \
    $$PWD/1.2.5/src/../ed25519/src/key_exchange.cpp \
    $$PWD/1.2.5/src/../ed25519/src/keypair.cpp \
    $$PWD/1.2.5/src/../ed25519/src/sc.cpp \
    $$PWD/1.2.5/src/../ed25519/src/sign.cpp \
    $$PWD/1.2.5/src/../ed25519/src/verify.cpp

LIBTORRENT_SOURCES += \
    $$PWD/1.2.5/src/hasher512.cpp

LIBTORRENT_HEADERS += \
    $$PWD/1.2.5/include/libtorrent/add_torrent_params.hpp \
    $$PWD/1.2.5/include/libtorrent/address.hpp \
    $$PWD/1.2.5/include/libtorrent/alert.hpp \
    $$PWD/1.2.5/include/libtorrent/alert_manager.hpp \
    $$PWD/1.2.5/include/libtorrent/alert_types.hpp \
    $$PWD/1.2.5/include/libtorrent/announce_entry.hpp \
    $$PWD/1.2.5/include/libtorrent/assert.hpp \
    $$PWD/1.2.5/include/libtorrent/bandwidth_limit.hpp \
    $$PWD/1.2.5/include/libtorrent/bandwidth_manager.hpp \
    $$PWD/1.2.5/include/libtorrent/bandwidth_queue_entry.hpp \
    $$PWD/1.2.5/include/libtorrent/bandwidth_socket.hpp \
    $$PWD/1.2.5/include/libtorrent/bdecode.hpp \
    $$PWD/1.2.5/include/libtorrent/bencode.hpp \
    $$PWD/1.2.5/include/libtorrent/bitfield.hpp \
    $$PWD/1.2.5/include/libtorrent/block_cache.hpp \
    $$PWD/1.2.5/include/libtorrent/bloom_filter.hpp \
    $$PWD/1.2.5/include/libtorrent/broadcast_socket.hpp \
    $$PWD/1.2.5/include/libtorrent/bt_peer_connection.hpp \
    $$PWD/1.2.5/include/libtorrent/buffer.hpp \
    $$PWD/1.2.5/include/libtorrent/chained_buffer.hpp \
    $$PWD/1.2.5/include/libtorrent/choker.hpp \
    $$PWD/1.2.5/include/libtorrent/close_reason.hpp \
    $$PWD/1.2.5/include/libtorrent/config.hpp \
    $$PWD/1.2.5/include/libtorrent/ConvertUTF.h \
    $$PWD/1.2.5/include/libtorrent/copy_ptr.hpp \
    $$PWD/1.2.5/include/libtorrent/crc32c.hpp \
    $$PWD/1.2.5/include/libtorrent/create_torrent.hpp \
    $$PWD/1.2.5/include/libtorrent/deadline_timer.hpp \
    $$PWD/1.2.5/include/libtorrent/debug.hpp \
    $$PWD/1.2.5/include/libtorrent/disk_buffer_holder.hpp \
    $$PWD/1.2.5/include/libtorrent/disk_buffer_pool.hpp \
    $$PWD/1.2.5/include/libtorrent/disk_interface.hpp \
    $$PWD/1.2.5/include/libtorrent/disk_io_job.hpp \
    $$PWD/1.2.5/include/libtorrent/disk_io_thread.hpp \
    $$PWD/1.2.5/include/libtorrent/disk_io_thread_pool.hpp \
    $$PWD/1.2.5/include/libtorrent/disk_job_pool.hpp \
    $$PWD/1.2.5/include/libtorrent/disk_observer.hpp \
    $$PWD/1.2.5/include/libtorrent/download_priority.hpp \
    $$PWD/1.2.5/include/libtorrent/ed25519.hpp \
    $$PWD/1.2.5/include/libtorrent/entry.hpp \
    $$PWD/1.2.5/include/libtorrent/enum_net.hpp \
    $$PWD/1.2.5/include/libtorrent/error.hpp \
    $$PWD/1.2.5/include/libtorrent/error_code.hpp \
    $$PWD/1.2.5/include/libtorrent/extensions.hpp \
    $$PWD/1.2.5/include/libtorrent/file.hpp \
    $$PWD/1.2.5/include/libtorrent/file_pool.hpp \
    $$PWD/1.2.5/include/libtorrent/file_storage.hpp \
    $$PWD/1.2.5/include/libtorrent/fingerprint.hpp \
    $$PWD/1.2.5/include/libtorrent/flags.hpp \
    $$PWD/1.2.5/include/libtorrent/fwd.hpp \
    $$PWD/1.2.5/include/libtorrent/gzip.hpp \
    $$PWD/1.2.5/include/libtorrent/hasher.hpp \
    $$PWD/1.2.5/include/libtorrent/hasher512.hpp \
    $$PWD/1.2.5/include/libtorrent/heterogeneous_queue.hpp \
    $$PWD/1.2.5/include/libtorrent/hex.hpp \
    $$PWD/1.2.5/include/libtorrent/http_connection.hpp \
    $$PWD/1.2.5/include/libtorrent/http_parser.hpp \
    $$PWD/1.2.5/include/libtorrent/http_seed_connection.hpp \
    $$PWD/1.2.5/include/libtorrent/http_stream.hpp \
    $$PWD/1.2.5/include/libtorrent/http_tracker_connection.hpp \
    $$PWD/1.2.5/include/libtorrent/i2p_stream.hpp \
    $$PWD/1.2.5/include/libtorrent/identify_client.hpp \
    $$PWD/1.2.5/include/libtorrent/index_range.hpp \
    $$PWD/1.2.5/include/libtorrent/invariant_check.hpp \
    $$PWD/1.2.5/include/libtorrent/io.hpp \
    $$PWD/1.2.5/include/libtorrent/io_service.hpp \
    $$PWD/1.2.5/include/libtorrent/io_service_fwd.hpp \
    $$PWD/1.2.5/include/libtorrent/ip_filter.hpp \
    $$PWD/1.2.5/include/libtorrent/ip_voter.hpp \
    $$PWD/1.2.5/include/libtorrent/lazy_entry.hpp \
    $$PWD/1.2.5/include/libtorrent/link.hpp \
    $$PWD/1.2.5/include/libtorrent/linked_list.hpp \
    $$PWD/1.2.5/include/libtorrent/lsd.hpp \
    $$PWD/1.2.5/include/libtorrent/magnet_uri.hpp \
    $$PWD/1.2.5/include/libtorrent/natpmp.hpp \
    $$PWD/1.2.5/include/libtorrent/netlink.hpp \
    $$PWD/1.2.5/include/libtorrent/operations.hpp \
    $$PWD/1.2.5/include/libtorrent/optional.hpp \
    $$PWD/1.2.5/include/libtorrent/packet_buffer.hpp \
    $$PWD/1.2.5/include/libtorrent/packet_pool.hpp \
    $$PWD/1.2.5/include/libtorrent/parse_url.hpp \
    $$PWD/1.2.5/include/libtorrent/part_file.hpp \
    $$PWD/1.2.5/include/libtorrent/pe_crypto.hpp \
    $$PWD/1.2.5/include/libtorrent/peer.hpp \
    $$PWD/1.2.5/include/libtorrent/peer_class.hpp \
    $$PWD/1.2.5/include/libtorrent/peer_class_set.hpp \
    $$PWD/1.2.5/include/libtorrent/peer_class_type_filter.hpp \
    $$PWD/1.2.5/include/libtorrent/peer_connection.hpp \
    $$PWD/1.2.5/include/libtorrent/peer_connection_handle.hpp \
    $$PWD/1.2.5/include/libtorrent/peer_connection_interface.hpp \
    $$PWD/1.2.5/include/libtorrent/peer_id.hpp \
    $$PWD/1.2.5/include/libtorrent/peer_info.hpp \
    $$PWD/1.2.5/include/libtorrent/peer_list.hpp \
    $$PWD/1.2.5/include/libtorrent/peer_request.hpp \
    $$PWD/1.2.5/include/libtorrent/performance_counters.hpp \
    $$PWD/1.2.5/include/libtorrent/pex_flags.hpp \
    $$PWD/1.2.5/include/libtorrent/piece_block.hpp \
    $$PWD/1.2.5/include/libtorrent/piece_block_progress.hpp \
    $$PWD/1.2.5/include/libtorrent/piece_picker.hpp \
    $$PWD/1.2.5/include/libtorrent/platform_util.hpp \
    $$PWD/1.2.5/include/libtorrent/portmap.hpp \
    $$PWD/1.2.5/include/libtorrent/proxy_base.hpp \
    $$PWD/1.2.5/include/libtorrent/puff.hpp \
    $$PWD/1.2.5/include/libtorrent/random.hpp \
    $$PWD/1.2.5/include/libtorrent/read_resume_data.hpp \
    $$PWD/1.2.5/include/libtorrent/receive_buffer.hpp \
    $$PWD/1.2.5/include/libtorrent/request_blocks.hpp \
    $$PWD/1.2.5/include/libtorrent/resolve_links.hpp \
    $$PWD/1.2.5/include/libtorrent/resolver.hpp \
    $$PWD/1.2.5/include/libtorrent/resolver_interface.hpp \
    $$PWD/1.2.5/include/libtorrent/session.hpp \
    $$PWD/1.2.5/include/libtorrent/session_handle.hpp \
    $$PWD/1.2.5/include/libtorrent/session_settings.hpp \
    $$PWD/1.2.5/include/libtorrent/session_stats.hpp \
    $$PWD/1.2.5/include/libtorrent/session_status.hpp \
    $$PWD/1.2.5/include/libtorrent/session_types.hpp \
    $$PWD/1.2.5/include/libtorrent/settings_pack.hpp \
    $$PWD/1.2.5/include/libtorrent/sha1.hpp \
    $$PWD/1.2.5/include/libtorrent/sha1_hash.hpp \
    $$PWD/1.2.5/include/libtorrent/sha512.hpp \
    $$PWD/1.2.5/include/libtorrent/sliding_average.hpp \
    $$PWD/1.2.5/include/libtorrent/socket.hpp \
    $$PWD/1.2.5/include/libtorrent/socket_io.hpp \
    $$PWD/1.2.5/include/libtorrent/socks5_stream.hpp \
    $$PWD/1.2.5/include/libtorrent/span.hpp \
    $$PWD/1.2.5/include/libtorrent/ssl_stream.hpp \
    $$PWD/1.2.5/include/libtorrent/stack_allocator.hpp \
    $$PWD/1.2.5/include/libtorrent/stat.hpp \
    $$PWD/1.2.5/include/libtorrent/stat_cache.hpp \
    $$PWD/1.2.5/include/libtorrent/storage.hpp \
    $$PWD/1.2.5/include/libtorrent/storage_defs.hpp \
    $$PWD/1.2.5/include/libtorrent/string_util.hpp \
    $$PWD/1.2.5/include/libtorrent/string_view.hpp \
    $$PWD/1.2.5/include/libtorrent/tailqueue.hpp \
    $$PWD/1.2.5/include/libtorrent/time.hpp \
    $$PWD/1.2.5/include/libtorrent/timestamp_history.hpp \
    $$PWD/1.2.5/include/libtorrent/torrent.hpp \
    $$PWD/1.2.5/include/libtorrent/torrent_flags.hpp \
    $$PWD/1.2.5/include/libtorrent/torrent_handle.hpp \
    $$PWD/1.2.5/include/libtorrent/torrent_info.hpp \
    $$PWD/1.2.5/include/libtorrent/torrent_peer.hpp \
    $$PWD/1.2.5/include/libtorrent/torrent_peer_allocator.hpp \
    $$PWD/1.2.5/include/libtorrent/torrent_status.hpp \
    $$PWD/1.2.5/include/libtorrent/tracker_manager.hpp \
    $$PWD/1.2.5/include/libtorrent/udp_socket.hpp \
    $$PWD/1.2.5/include/libtorrent/udp_tracker_connection.hpp \
    $$PWD/1.2.5/include/libtorrent/union_endpoint.hpp \
    $$PWD/1.2.5/include/libtorrent/units.hpp \
    $$PWD/1.2.5/include/libtorrent/upnp.hpp \
    $$PWD/1.2.5/include/libtorrent/utf8.hpp \
    $$PWD/1.2.5/include/libtorrent/utp_socket_manager.hpp \
    $$PWD/1.2.5/include/libtorrent/utp_stream.hpp \
    $$PWD/1.2.5/include/libtorrent/vector_utils.hpp \
    $$PWD/1.2.5/include/libtorrent/version.hpp \
    $$PWD/1.2.5/include/libtorrent/web_connection_base.hpp \
    $$PWD/1.2.5/include/libtorrent/web_peer_connection.hpp \
    $$PWD/1.2.5/include/libtorrent/write_resume_data.hpp \
    $$PWD/1.2.5/include/libtorrent/xml_parse.hpp

LIBTORRENT_HEADERS += \
    $$PWD/1.2.5/include/libtorrent/extensions/smart_ban.hpp \
    $$PWD/1.2.5/include/libtorrent/extensions/ut_metadata.hpp \
    $$PWD/1.2.5/include/libtorrent/extensions/ut_pex.hpp

LIBTORRENT_HEADERS += \
    $$PWD/1.2.5/include/libtorrent/aux_/aligned_storage.hpp \
    $$PWD/1.2.5/include/libtorrent/aux_/aligned_union.hpp \
    $$PWD/1.2.5/include/libtorrent/aux_/alloca.hpp \
    $$PWD/1.2.5/include/libtorrent/aux_/allocating_handler.hpp \
    $$PWD/1.2.5/include/libtorrent/aux_/array.hpp \
    $$PWD/1.2.5/include/libtorrent/aux_/bind_to_device.hpp \
    $$PWD/1.2.5/include/libtorrent/aux_/keepalive.hpp \
    $$PWD/1.2.5/include/libtorrent/aux_/block_cache_reference.hpp \
    $$PWD/1.2.5/include/libtorrent/aux_/byteswap.hpp \
    $$PWD/1.2.5/include/libtorrent/aux_/cppint_import_export.hpp \
    $$PWD/1.2.5/include/libtorrent/aux_/cpuid.hpp \
    $$PWD/1.2.5/include/libtorrent/aux_/deferred_handler.hpp \
    $$PWD/1.2.5/include/libtorrent/aux_/deprecated.hpp \
    $$PWD/1.2.5/include/libtorrent/aux_/deque.hpp \
    $$PWD/1.2.5/include/libtorrent/aux_/dev_random.hpp \
    $$PWD/1.2.5/include/libtorrent/aux_/disable_warnings_pop.hpp \
    $$PWD/1.2.5/include/libtorrent/aux_/disable_warnings_push.hpp \
    $$PWD/1.2.5/include/libtorrent/aux_/disk_job_fence.hpp \
    $$PWD/1.2.5/include/libtorrent/aux_/escape_string.hpp \
    $$PWD/1.2.5/include/libtorrent/aux_/export.hpp \
    $$PWD/1.2.5/include/libtorrent/aux_/ffs.hpp \
    $$PWD/1.2.5/include/libtorrent/aux_/file_progress.hpp \
    $$PWD/1.2.5/include/libtorrent/aux_/has_block.hpp \
    $$PWD/1.2.5/include/libtorrent/aux_/instantiate_connection.hpp \
    $$PWD/1.2.5/include/libtorrent/aux_/io.hpp \
    $$PWD/1.2.5/include/libtorrent/aux_/ip_notifier.hpp \
    $$PWD/1.2.5/include/libtorrent/aux_/listen_socket_handle.hpp \
    $$PWD/1.2.5/include/libtorrent/aux_/lsd.hpp \
    $$PWD/1.2.5/include/libtorrent/aux_/merkle.hpp \
    $$PWD/1.2.5/include/libtorrent/aux_/noexcept_movable.hpp \
    $$PWD/1.2.5/include/libtorrent/aux_/numeric_cast.hpp \
    $$PWD/1.2.5/include/libtorrent/aux_/openssl.hpp \
    $$PWD/1.2.5/include/libtorrent/aux_/path.hpp \
    $$PWD/1.2.5/include/libtorrent/aux_/portmap.hpp \
    $$PWD/1.2.5/include/libtorrent/aux_/proxy_settings.hpp \
    $$PWD/1.2.5/include/libtorrent/aux_/range.hpp \
    $$PWD/1.2.5/include/libtorrent/aux_/route.h \
    $$PWD/1.2.5/include/libtorrent/aux_/scope_end.hpp \
    $$PWD/1.2.5/include/libtorrent/aux_/session_call.hpp \
    $$PWD/1.2.5/include/libtorrent/aux_/session_impl.hpp \
    $$PWD/1.2.5/include/libtorrent/aux_/session_interface.hpp \
    $$PWD/1.2.5/include/libtorrent/aux_/session_settings.hpp \
    $$PWD/1.2.5/include/libtorrent/aux_/session_udp_sockets.hpp \
    $$PWD/1.2.5/include/libtorrent/aux_/set_socket_buffer.hpp \
    $$PWD/1.2.5/include/libtorrent/aux_/socket_type.hpp \
    $$PWD/1.2.5/include/libtorrent/aux_/storage_piece_set.hpp \
    $$PWD/1.2.5/include/libtorrent/aux_/storage_utils.hpp \
    $$PWD/1.2.5/include/libtorrent/aux_/string_ptr.hpp \
    $$PWD/1.2.5/include/libtorrent/aux_/suggest_piece.hpp \
    $$PWD/1.2.5/include/libtorrent/aux_/throw.hpp \
    $$PWD/1.2.5/include/libtorrent/aux_/time.hpp \
    $$PWD/1.2.5/include/libtorrent/aux_/torrent_impl.hpp \
    $$PWD/1.2.5/include/libtorrent/aux_/unique_ptr.hpp \
    $$PWD/1.2.5/include/libtorrent/aux_/vector.hpp \
    $$PWD/1.2.5/include/libtorrent/aux_/win_crypto_provider.hpp \
    $$PWD/1.2.5/include/libtorrent/aux_/win_util.hpp

LIBTORRENT_SOURCES += \
    $$PWD/1.2.5/src/web_connection_base.cpp \
    $$PWD/1.2.5/src/alert.cpp \
    $$PWD/1.2.5/src/alert_manager.cpp \
    $$PWD/1.2.5/src/announce_entry.cpp \
    $$PWD/1.2.5/src/assert.cpp \
    $$PWD/1.2.5/src/bandwidth_limit.cpp \
    $$PWD/1.2.5/src/bandwidth_manager.cpp \
    $$PWD/1.2.5/src/bandwidth_queue_entry.cpp \
    $$PWD/1.2.5/src/bdecode.cpp \
    $$PWD/1.2.5/src/bitfield.cpp \
    $$PWD/1.2.5/src/bloom_filter.cpp \
    $$PWD/1.2.5/src/broadcast_socket.cpp \
    $$PWD/1.2.5/src/block_cache.cpp \
    $$PWD/1.2.5/src/bt_peer_connection.cpp \
    $$PWD/1.2.5/src/chained_buffer.cpp \
    $$PWD/1.2.5/src/choker.cpp \
    $$PWD/1.2.5/src/close_reason.cpp \
    $$PWD/1.2.5/src/ConvertUTF.cpp \
    $$PWD/1.2.5/src/cpuid.cpp \
    $$PWD/1.2.5/src/crc32c.cpp \
    $$PWD/1.2.5/src/create_torrent.cpp \
    $$PWD/1.2.5/src/disk_buffer_holder.cpp \
    $$PWD/1.2.5/src/disk_buffer_pool.cpp \
    $$PWD/1.2.5/src/disk_io_job.cpp \
    $$PWD/1.2.5/src/disk_io_thread.cpp \
    $$PWD/1.2.5/src/disk_io_thread_pool.cpp \
    $$PWD/1.2.5/src/disk_job_fence.cpp \
    $$PWD/1.2.5/src/disk_job_pool.cpp \
    $$PWD/1.2.5/src/entry.cpp \
    $$PWD/1.2.5/src/enum_net.cpp \
    $$PWD/1.2.5/src/error_code.cpp \
    $$PWD/1.2.5/src/escape_string.cpp \
    $$PWD/1.2.5/src/file.cpp \
    $$PWD/1.2.5/src/path.cpp \
    $$PWD/1.2.5/src/file_pool.cpp \
    $$PWD/1.2.5/src/file_storage.cpp \
    $$PWD/1.2.5/src/fingerprint.cpp \
    $$PWD/1.2.5/src/generate_peer_id.cpp \
    $$PWD/1.2.5/src/gzip.cpp \
    $$PWD/1.2.5/src/hasher.cpp \
    $$PWD/1.2.5/src/hex.cpp \
    $$PWD/1.2.5/src/http_connection.cpp \
    $$PWD/1.2.5/src/http_parser.cpp \
    $$PWD/1.2.5/src/http_seed_connection.cpp \
    $$PWD/1.2.5/src/http_stream.cpp \
    $$PWD/1.2.5/src/http_tracker_connection.cpp \
    $$PWD/1.2.5/src/i2p_stream.cpp \
    $$PWD/1.2.5/src/identify_client.cpp \
    $$PWD/1.2.5/src/instantiate_connection.cpp \
    $$PWD/1.2.5/src/ip_filter.cpp \
    $$PWD/1.2.5/src/ip_notifier.cpp \
    $$PWD/1.2.5/src/ip_voter.cpp \
    $$PWD/1.2.5/src/lazy_bdecode.cpp \
    $$PWD/1.2.5/src/listen_socket_handle.cpp \
    $$PWD/1.2.5/src/lsd.cpp \
    $$PWD/1.2.5/src/magnet_uri.cpp \
    $$PWD/1.2.5/src/merkle.cpp \
    $$PWD/1.2.5/src/natpmp.cpp \
    $$PWD/1.2.5/src/parse_url.cpp \
    $$PWD/1.2.5/src/part_file.cpp \
    $$PWD/1.2.5/src/pe_crypto.cpp \
    $$PWD/1.2.5/src/performance_counters.cpp \
    $$PWD/1.2.5/src/peer_connection.cpp \
    $$PWD/1.2.5/src/peer_connection_handle.cpp \
    $$PWD/1.2.5/src/peer_class.cpp \
    $$PWD/1.2.5/src/peer_class_set.cpp \
    $$PWD/1.2.5/src/piece_picker.cpp \
    $$PWD/1.2.5/src/platform_util.cpp \
    $$PWD/1.2.5/src/packet_buffer.cpp \
    $$PWD/1.2.5/src/proxy_base.cpp \
    $$PWD/1.2.5/src/peer_list.cpp \
    $$PWD/1.2.5/src/puff.cpp \
    $$PWD/1.2.5/src/random.cpp \
    $$PWD/1.2.5/src/receive_buffer.cpp \
    $$PWD/1.2.5/src/read_resume_data.cpp \
    $$PWD/1.2.5/src/write_resume_data.cpp \
    $$PWD/1.2.5/src/request_blocks.cpp \
    $$PWD/1.2.5/src/resolve_links.cpp \
    $$PWD/1.2.5/src/resolver.cpp \
    $$PWD/1.2.5/src/session.cpp \
    $$PWD/1.2.5/src/session_call.cpp \
    $$PWD/1.2.5/src/session_handle.cpp \
    $$PWD/1.2.5/src/session_impl.cpp \
    $$PWD/1.2.5/src/session_settings.cpp \
    $$PWD/1.2.5/src/proxy_settings.cpp \
    $$PWD/1.2.5/src/settings_pack.cpp \
    $$PWD/1.2.5/src/sha1_hash.cpp \
    $$PWD/1.2.5/src/smart_ban.cpp \
    $$PWD/1.2.5/src/socket_io.cpp \
    $$PWD/1.2.5/src/socket_type.cpp \
    $$PWD/1.2.5/src/socks5_stream.cpp \
    $$PWD/1.2.5/src/stat.cpp \
    $$PWD/1.2.5/src/stat_cache.cpp \
    $$PWD/1.2.5/src/storage.cpp \
    $$PWD/1.2.5/src/storage_piece_set.cpp \
    $$PWD/1.2.5/src/storage_utils.cpp \
    $$PWD/1.2.5/src/session_stats.cpp \
    $$PWD/1.2.5/src/string_util.cpp \
    $$PWD/1.2.5/src/torrent.cpp \
    $$PWD/1.2.5/src/torrent_handle.cpp \
    $$PWD/1.2.5/src/torrent_info.cpp \
    $$PWD/1.2.5/src/torrent_peer.cpp \
    $$PWD/1.2.5/src/torrent_peer_allocator.cpp \
    $$PWD/1.2.5/src/torrent_status.cpp \
    $$PWD/1.2.5/src/time.cpp \
    $$PWD/1.2.5/src/timestamp_history.cpp \
    $$PWD/1.2.5/src/tracker_manager.cpp \
    $$PWD/1.2.5/src/udp_socket.cpp \
    $$PWD/1.2.5/src/udp_tracker_connection.cpp \
    $$PWD/1.2.5/src/upnp.cpp \
    $$PWD/1.2.5/src/ut_metadata.cpp \
    $$PWD/1.2.5/src/ut_pex.cpp \
    $$PWD/1.2.5/src/utf8.cpp \
    $$PWD/1.2.5/src/utp_socket_manager.cpp \
    $$PWD/1.2.5/src/utp_stream.cpp \
    $$PWD/1.2.5/src/web_peer_connection.cpp \
    $$PWD/1.2.5/src/xml_parse.cpp \
    $$PWD/1.2.5/src/version.cpp \
    $$PWD/1.2.5/src/file_progress.cpp \
    $$PWD/1.2.5/src/ffs.cpp \
    $$PWD/1.2.5/src/add_torrent_params.cpp \
    $$PWD/1.2.5/src/peer_info.cpp \
    $$PWD/1.2.5/src/stack_allocator.cpp \
    $$PWD/1.2.5/src/sha1.cpp

LIBTORRENT_SOURCES += \
    $$PWD/1.2.5/src/sha512.cpp

#OTHERS+= Makefile.am
