[Icon Theme]
Name=default
Comment=Icon theme with a classic look (light mode)

Directories=16x16/actions,24x24/actions,26x26/actions,32x32/actions,48x48/actions

[16x16/actions]
Size=16
Context=Actions
Type=Fixed

[24x24/actions]
Size=24
Context=Actions
Type=Fixed

[26x26/actions]
Size=26
Context=Actions
Type=Fixed

[32x32/actions]
Size=32
Context=Actions
Type=Fixed

[48x48/actions]
Size=48
Context=Actions
Type=Fixed
